In [1]:
import networkx as nx
import numpy as np

In [2]:
g=nx.Graph()

In [3]:
g.add_edges_from([(1,2),(2,4),(1,3),(3,4),(4,5)])
for e in g: 
    print e


1
2
3
4
5


In [39]:
print nx.edge_current_flow_betweenness_centrality_subset(g,[1],[2],normalized=False)

print nx.current_flow_betweenness_centrality_subset(g,[1],[2],normalized=False)

{(4, 5): 0.0, (1, 2): 0.1875, (1, 3): 0.0625, (3, 4): 0.0625, (2, 4): 0.0625}
{1: -0.083333333333333315, 2: -0.083333333333333315, 3: -0.20833333333333331, 4: -0.20833333333333331, 5: -0.33333333333333331}


In [26]:
print nx.edge_current_flow_betweenness_centrality(g,normalized=True)

print nx.current_flow_betweenness_centrality(g,normalized=True)

{(4, 5): 0.3333333333333333, (1, 2): 0.2916666666666667, (1, 3): 0.2916666666666667, (3, 4): 0.3333333333333333, (2, 4): 0.3333333333333333}
{1: 0.25, 2: 0.2916666666666667, 3: 0.2916666666666667, 4: 0.6666666666666666, 5: 0.0}


In [4]:
L=nx.laplacian_matrix(g)
l=L.todense()
n=g.number_of_nodes()
print l,n
l=np.delete(l,0,axis=0)
l=np.delete(l,0,axis=1)
print l
v=np.linalg.inv(l)
print v
t=np.zeros((n,n))
t[1:,1:]=v
print t

T=dict.fromkeys(g.nodes(),{})
i_count=0
for i in T:
    T[i]=dict.fromkeys(g.nodes(),0.0)
    j_count=0
    for j in T[i]:
        T[i][j]=t[i_count][j_count]
        j_count+=1
    i_count+=1
    
print T
    


[[ 2 -1 -1  0  0]
 [-1  2  0 -1  0]
 [-1  0  2 -1  0]
 [ 0 -1 -1  3 -1]
 [ 0  0  0 -1  1]] 5
[[ 2  0 -1  0]
 [ 0  2 -1  0]
 [-1 -1  3 -1]
 [ 0  0 -1  1]]
[[ 0.75  0.25  0.5   0.5 ]
 [ 0.25  0.75  0.5   0.5 ]
 [ 0.5   0.5   1.    1.  ]
 [ 0.5   0.5   1.    2.  ]]
[[ 0.    0.    0.    0.    0.  ]
 [ 0.    0.75  0.25  0.5   0.5 ]
 [ 0.    0.25  0.75  0.5   0.5 ]
 [ 0.    0.5   0.5   1.    1.  ]
 [ 0.    0.5   0.5   1.    2.  ]]
{1: {1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0}, 2: {1: 0.0, 2: 0.75, 3: 0.25, 4: 0.5, 5: 0.5}, 3: {1: 0.0, 2: 0.25, 3: 0.75, 4: 0.5, 5: 0.5}, 4: {1: 0.0, 2: 0.5, 3: 0.5, 4: 1.0, 5: 1.0}, 5: {1: 0.0, 2: 0.5, 3: 0.5, 4: 1.0, 5: 2.0}}


In [10]:
seen=[]

V=dict.fromkeys(g.nodes(),{})
print V

for s in V:
    V[s]=dict.fromkeys(list(set(g.nodes())-set(seen)),{})
    seen.append(s)
    for t in V[s]:
        V[s][t]=dict.fromkeys(g.nodes(),{})
        for i in g.nodes():
            V[s][t][i]=T[i][s]-T[i][t]
    
for s in V:
    for t in V[s]:
        print s,t,V[s][t]

{1: {}, 2: {}, 3: {}, 4: {}, 5: {}}
1 1 {1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0}
1 2 {1: 0.0, 2: -0.75, 3: -0.25, 4: -0.5, 5: -0.5}
1 3 {1: 0.0, 2: -0.25, 3: -0.75, 4: -0.5, 5: -0.5}
1 4 {1: 0.0, 2: -0.5, 3: -0.5, 4: -1.0, 5: -1.0}
1 5 {1: 0.0, 2: -0.5, 3: -0.5, 4: -1.0, 5: -2.0}
2 2 {1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0}
2 3 {1: 0.0, 2: 0.5, 3: -0.5, 4: 0.0, 5: 0.0}
2 4 {1: 0.0, 2: 0.25, 3: -0.25, 4: -0.5, 5: -0.5}
2 5 {1: 0.0, 2: 0.25, 3: -0.25, 4: -0.5, 5: -1.5}
3 3 {1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0}
3 4 {1: 0.0, 2: -0.25, 3: 0.25, 4: -0.5, 5: -0.5}
3 5 {1: 0.0, 2: -0.25, 3: 0.25, 4: -0.5, 5: -1.5}
4 4 {1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0}
4 5 {1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: -1.0}
5 5 {1: 0.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0}


In [12]:
keys=g.nodes()
keys.extend(g.edges())

I=dict.fromkeys(g.nodes(),{})
print I

for s in V:
    I[s]=dict.fromkeys(V[s],{})
    for t in V[s]:
        I[s][t]=dict.fromkeys(keys,{})
        for i in g.nodes():
            I[s][t][i]=0.0    
            if i==t or i==s:
                I[s][t][i]=1.0
            else:
                I[s][t][i]=0.0
                for j in g.neighbors(i):
                    I[s][t][i]+=.5*abs(T[i][s]-T[i][t]-T[j][s]+T[j][t])
        
        for e in g.edges():
            I[s][t][e]=abs(T[e[0]][s]-T[e[0]][t]-T[e[1]][s]+T[e[1]][t])
            
                
                
for s in I:
    for t in I[s]:
        print s,t,I[s][t]

{1: {}, 2: {}, 3: {}, 4: {}, 5: {}}
1 1 {(1, 2): 0.0, 1: 1.0, 2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0, (4, 5): 0.0, (1, 3): 0.0, (3, 4): 0.0, (2, 4): 0.0}
1 2 {(1, 2): 0.75, 1: 1.0, 2: 1.0, 3: 0.25, 4: 0.25, 5: 0.0, (4, 5): 0.0, (1, 3): 0.25, (3, 4): 0.25, (2, 4): 0.25}
1 3 {(1, 2): 0.25, 1: 1.0, 2: 0.25, 3: 1.0, 4: 0.25, 5: 0.0, (4, 5): 0.0, (1, 3): 0.75, (3, 4): 0.25, (2, 4): 0.25}
1 4 {(1, 2): 0.5, 1: 1.0, 2: 0.5, 3: 0.5, 4: 1.0, 5: 0.0, (4, 5): 0.0, (1, 3): 0.5, (3, 4): 0.5, (2, 4): 0.5}
1 5 {(1, 2): 0.5, 1: 1.0, 2: 0.5, 3: 0.5, 4: 1.0, 5: 1.0, (4, 5): 1.0, (1, 3): 0.5, (3, 4): 0.5, (2, 4): 0.5}
2 2 {(1, 2): 0.0, 1: 0.0, 2: 1.0, 3: 0.0, 4: 0.0, 5: 0.0, (4, 5): 0.0, (1, 3): 0.0, (3, 4): 0.0, (2, 4): 0.0}
2 3 {(1, 2): 0.5, 1: 0.5, 2: 1.0, 3: 1.0, 4: 0.5, 5: 0.0, (4, 5): 0.0, (1, 3): 0.5, (3, 4): 0.5, (2, 4): 0.5}
2 4 {(1, 2): 0.25, 1: 0.25, 2: 1.0, 3: 0.25, 4: 1.0, 5: 0.0, (4, 5): 0.0, (1, 3): 0.25, (3, 4): 0.25, (2, 4): 0.75}
2 5 {(1, 2): 0.25, 1: 0.25, 2: 1.0, 3: 0.25, 4: 1.0, 5: 1.0, (4, 5

In [7]:
g.nodes()

[1, 2, 3, 4, 5]